[profile.default]
src = "src"
out = "out"
via_ir = true
libs = ["lib"]

remappings = [ "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
               "forge-std/=lib/forge-std/src/",
               "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
               "@solmate=lib/solmate/src/",
               "foundry-devops/src=lib/foundry-devops/src"
            ]
fs_permissions = [{ access = "read", path = "./broadcast" }]
ffi = true
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
mainnet = "${INFURA_MAINNET_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
arbitrum = "${ARBITRUM_ALCHEMY_RPC_URL}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
holesky = "${HOLESKY_RPC_URL}"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
