[profile.default]
src = "src"
out = "out"
via_ir = true
libs = ["lib"]
solc-version = "0.8.20"
optimizer = true
optimizer-runs = 200
auto_detect_remappings = false  # 禁用自动检测
remappings = [ "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
               "forge-std/=lib/forge-std/src/",
               "foundry-devops/src/=lib/foundry-devops/src/",
               "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
               "@solmate=lib/solmate/src/",
               "foundry-devops/src=lib/foundry-devops/src",
               "@uniswap/v3-periphery/contracts/=lib/v3-periphery/contracts/",
               "@uniswap/v3-core/contracts/=lib/v3-core/contracts/",
               "@uniswap/swap-router-contracts/contracts/=lib/swap-router-contracts/contracts/"
            ]
fs_permissions = [{ access = "read", path = "./broadcast" }]
# ffi = true

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
mainnet = "${INFURA_MAINNET_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
arbitrum = "${ARBITRUM_ALCHEMY_RPC_URL}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
holesky = "${HOLESKY_RPC_URL}"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
